### ISSUE TITLE
Add genre to track search 

### ISSUE THREAD

**Issue by dannijt** [fernandabruno/musixmatchR#1]

**Comment by fernandabruno** [comment]
Feature added =)

**Comment by dannijt** [comment]
thank you

**Comment by dannijt** [comment]
Hello, 
thanks for your response! it appears it isn't working for me and in the code it looks like  the genre section was actually removed? Let me know if I am not looking in the right place. Thank you.

**Comment by fernandabruno** [comment]
Hello!
You are right: I added the feature without testing it enough. I notice that there's a problem with the list based on the genre. I am adjusting it this weekend.

Sorry for the trouble =/

**Comment by dannijt** [comment]
okay no worries : )

**Comment by fernandabruno** [comment]
Solution included. Please, try it to see if it helps you now =)

**Comment by dannijt** [comment]
Thank you! this works

**Comment by dannijt** [comment]
In your opinion, what is the best way to limit the print out to 1 or the closest values. I have been used head(x, 1) but there might be something more accurate. Let me know : )

**Comment by fernandabruno** [comment]
Glad that helped! 
I can add a new column with the first genre, does it help you?

**Comment by dannijt** [comment]
Hello! 
Thank you so much for editing this for me. I have a question and I've been struggling for a while. I Was wondering if you had time to answer a question for me. 


I am using your package to get song genre for a list of 3,000 tracks.  On a test sample, my function worked fine. But when i scaled up collection I am getting errors. And I think it because the API doesn't recognize the songs. I want to be able to still iterate over what the API DOES recognize and just return NA or an empty column for what isn't recognized rather than stopping the entire thing. 

```
Error in data.frame(metadata, substring(pos, 2)) : 
  arguments imply differing number of rows: 0, 1
```

**Comment by fernandabruno** [comment]
Probably you are using a Free MusixMatch Developer account.
This type of account is limited to 2k API Calls daily.

Do you think it makes sense?

**Comment by dannijt** [comment]
That does make sense which I will be looking out for in the future, but I get the same error message when I subset to 500. 
The error is that the output differs in the amount of variables in the input, which I think means one of the songs on my list isn't recognized.

**Comment by fernandabruno** [comment]
Do you mind sending me the search terms so I can test them here?

**Comment by dannijt** [comment]
Sure, all 3,000 of them?

**Comment by fernandabruno** [comment]
If you want to, you can send me them through email that is available on my profile page.

**Comment by fernandabruno** [comment]
I will make this genre issue solved and we can discuss the limit problem on another thread, ok?
